import Icons1 from "./data-icon1";
import Icons2 from "./data-icon2";
import Icons3 from "./data-icon3";
import Icons4 from "./data-icon4";

export const data = [
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "AMZN",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "TSLA",
    num: "200",
    perc: "-0.25%",
    riskLevel: "High Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "ABQQ",
    num: "200",
    perc: "-0.25%",
    riskLevel: "High Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "MSFT",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "PYPL",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "NFLX",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "NFLX",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "NFLX",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "NFLX",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
  {
    icon1: <Icons1 />,
    icon2: <Icons2 />,
    icon3: <Icons3 />,
    icon4: <Icons4 />,
    title: "NFLX",
    num: "200",
    perc: "-0.25%",
    riskLevel: "Low Risk",
  },
];
